---
- hosts: bootnode
  user: ubuntu
  become: True
  vars:
    nginx_headers: "on"
    PROXY_PORT: "8545"
    username: "bootnode"
    users:
      - name: "bootnode"
    home: "/home/bootnode"
  roles:
    - preconf
    - usermanager
    - nodejs
    - bootnode
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - poa-netstats
    - { role: poa-orchestrator, when: "(bootnode_orchestrator or 'off') == 'on'" }
    - nginx
    - bootnode-access
  tags:
    - bootnode
