---
- hosts: moc
  user: ubuntu
  become: True
  vars:
    username: "moc"
    users:
      - name: "moc"
    home: "/home/moc"
  roles:
    - preconf
    - usermanager
    - nodejs
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - poa-netstats
    - moc
    - moc-access
  tags:
    - moc
