---
- hosts: all
  user: ubuntu
  become: True
#  user: root
  roles:
    - preconf
  tags: preconf

- hosts: bootnode
  vars:
    nginx_headers: "on"
    PROXY_PORT: "8545"
    username: "bootnode"
    users:
      - name: "bootnode"
    home: "/home/bootnode"
#    logsprefix: "/home/{{ username }}/logs"
#    logentries_user_key: "0665901a-e843-41c5-82c1-2cc4b39f0b21"
  roles:
    - usermanager
#    - logentries
    - nodejs
    - { role: bootnode-parity, when: "BC_CLIENT == 'parity'" }
    - { role: bootnode-nethermind, when: "BC_CLIENT == 'nethermind'" }
    - poa-logrotate
    - { role: poa-parity, when: "BC_CLIENT == 'parity'" }
    - { role: poa-nethermind, when: "BC_CLIENT == 'nethermind'" }
    - poa-pm2
    - poa-netstats
    - { role: poa-orchestrator, when: "(bootnode_orchestrator or 'off') == 'on'" }
    - nginx
    - bootnode-access
  tags:
    - bootnode

- hosts: validator
  vars:
    username: "validator"
    users:
      - name: "validator"
    home: "/home/validator"
  roles:
    - usermanager
    - nodejs
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - poa-netstats
    - validator
    - validator-access
  tags:
    - validator

- hosts: netstat
  vars:
    nginx_headers: "off"
    PROXY_PORT: "3000"
    NETSTATS_SERVER: "http://localhost:3000"
    username: "netstat"
    users:
      - name: "netstat"
    home: "/home/netstat"
  roles:
    - usermanager
    - nodejs
    - poa-logrotate
    - netstat
    - nginx
    - netstat-access
  tags:
    - netstat

- hosts: explorer
  vars:
    nginx_headers: "off"
    PROXY_PORT: "3000"
    explorerS_SERVER: "localhost"
    username: "explorer"
    users:
      - name: "explorer"
    home: "/home/explorer"
  roles:
    - usermanager
    - nodejs
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - explorer
    - nginx
    - explorer-access
  tags:
    - explorer

- hosts: moc
  vars:
    username: "moc"
    users:
      - name: "moc"
    home: "/home/moc"
  roles:
    - usermanager
    - nodejs
    - poa-logrotate
    - poa-parity
    - poa-pm2
    - poa-netstats
    - moc
    - moc-access
  tags:
    - moc

- hosts: blockscout
  vars:
    username: "blockscout"
    users:
    - name: "blockscout"
    home: "/home/blockscout"
    nginx_headers: "off"
    PROXY_PORT: "4000"
  roles:
  - usermanager
  - nodejs
  - poa-parity
  - nginx
  - elixir
  - blockscout
  - blockscout-access
  tags:
  - blockscout
