version: 2
jobs:
  preconf:
    docker:
      - image: poanetwork/terraform-prep
    working_directory: ~/deployment-terraform/azure
    environment:
          ANSIBLE_AZURE_AUTH_SOURCE: env  
    
    steps:
      - run:
          name: Shout
          command: echo 'Yay'

workflows:
  version: 2
  full:
    jobs:
      - preconf
