---
- name: Install chrony package
  apt: name=chrony

- name: Select Amazon time server
  lineinfile:
    dest: /etc/chrony/chrony.conf
    insertafter: '^pool'
    line: 'server 169.254.169.123 prefer iburst'
    state: present

- name: Enable chrony service
  service:
    name: chrony
    state: restarted
    enabled: yes
