---

GENESIS_NETWORK_NAME: "PoA"
PARITY_BIN_LOC: "https://s3.us-east-2.amazonaws.com/poa-builds-parity-published/1.10.6/parity"                                          
PARITY_BIN_SHA256: "539f4788fbd605a9cd87b5bf747b27ae05b8a4080b26aa3da645b0446fa9f9cc"
ORCHESTRATOR_BIN_LOC: ""                                                                                                                
ORCHESTRATOR_BIN_SHA256: ""
 
validator_archive: "off"
bootnode_archive: "off"
moc_archive: "off"
bootnode_orchestrator: "off"

username: "poa"
users:
  - name: "{{ username }}"
home: "/home/{{ username }}"
